FROM golang:1.7

RUN wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
RUN tar xvfz glide-v0.12.3-linux-amd64.tar.gz
RUN cp /go/linux-amd64/glide /usr/local/bin/
